# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46d56dc40d5627fb9ee6c504989618b3cf6629e1e994d742262fae43ccdf2ae03d2558da2fa3df39387597bcbd1108405b749afee8212f21c9e54c66ab63a5ea

test:
  secret_key_base: 87540b4701ffd90b5f8208ee2c213310321b02c6dcda0324b74113351af9d04fc7c0d673b2bc37bdaef2ac22866e2d034b5359bd4731ef83d10b332b44f1093a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
